### ISSUE TITLE
SmartBone 2 appears to not be loading properly

### ISSUE THREAD

**Issue by axriel0** [CelnakRBLX/SmartBone-2#9] opened 2023-12-06 10:10 UTC
I've been trying to update the old SmartBone module in my game to the new SmartBone 2 module, however it seems to not be loading properly, as every bone in the SmartBone object is completely stiff when I play the game (I tried both playtesting and joining the game regularly, the SmartBone object is set up according to the documentation). I've been checking the output, however there hasn't been a single error. I also noticed that when I start up a copy of the Smartbone 2 place file, everything works perfectly while playtesting, but when I try creating a new baseplate and inserting the new scripts there, it still doesn't work so I am certain that the code in my other game is not interfering with the SmartBone module's code.

**Comment by JakeyWasTaken** [comment] 2023-12-06 11:25
I'm not sure what could be causing this, I've got a few questions though

* Are you calling .Start() in client context
* Are your objects tagged correctly

**Comment by axriel0** [comment] 2023-12-06 13:14
> I'm not sure what could be causing this, I've got a few questions though
> 
> * Are you calling .Start() in client context
> * Are your objects tagged correctly

Yes, as I said earlier; "the SmartBone object is set up according to the documentation". The object already has the tag SmartBone.
.Start() is being called from a LocalScript inside of StarterPlayerScripts, and the SmartBone module is inside  #ReplicatedStorage.

**Comment by JakeyWasTaken** [comment] 2023-12-06 14:02
Could you share a repro file?

**Comment by axriel0** [comment] 2023-12-06 14:13
> Could you share a repro file?

Sorry, what's a repro file? Never heard of it before, but I probably can.

**Comment by JakeyWasTaken** [comment] 2023-12-06 14:14
A place file which the same bug happens so I can test it

**Comment by JakeyWasTaken** [comment] 2023-12-06 22:39
I've figured out the cause for this, it will be fixed in the next release however it is now running into this issue https://github.com/CelnakRBLX/SmartBone-2/issues/10

**Comment by JakeyWasTaken** [comment] 2023-12-08 20:59
Fixed in [v0.1.1](https://github.com/CelnakRBLX/SmartBone-2/releases/tag/v0.1.1)

**Closed by JakeyWasTaken** 2023-12-08 20:59 UTC
Labels: bug
